# Generated by Django 3.1.2 on 2020-10-14 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('identificacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(max_length=45)),
                ('num_cuenta', models.CharField(max_length=45)),
                ('monto', models.IntegerField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cliente')),
            ],
        ),
    ]
